# Generated by Django 4.0.6 on 2022-07-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_becomelecturers_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%y')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
