# Generated by Django 4.0.6 on 2022-07-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_tutorblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorblock',
            name='content',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
