# Generated by Django 4.0.6 on 2022-07-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_tutorblock_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorblock',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='tutorblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
