# Generated by Django 4.0.6 on 2022-08-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_partners_partners2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
